sudo: required

branches:
  only:
  - master

env:
  global:
  - IMG_VERS=$(git rev-parse HEAD)

services:
- docker

install:
# Build images
- docker build -t jamese/logstash:latest -t jamese/logstash:$IMG_VERS ./logstash

script:
# Login to docker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push latest image to docker hub
- docker push jamese/logstash:latest
# Push unique image to docker hub
- docker push jamese/logstash:$IMG_VERS