version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch
  
  kibana:
    image: kibana:7.4.0
    ports:
      - 5601:5601
    container_name: kibana
    depends_on:
      - elasticsearch
  
  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    volumes:
      - ./logs:/usr/share/logstash/logs
    container_name: logstash
    depends_on:
      - elasticsearch
  